# Generated by Django 6.0.3 on 2026-06-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0003_servicecategory_remove_service_price_per_word_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='source_language',
        ),
        migrations.RemoveField(
            model_name='order',
            name='target_language',
        ),
        migrations.AddField(
            model_name='order',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Термінове замовлення'),
        ),
    ]
