# Generated by Django 6.0.3 on 2026-06-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0004_remove_order_source_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='orders/'),
        ),
    ]
