# Generated by Django 6.0.3 on 2026-06-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0005_order_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='file_path',
        ),
    ]
